[[kv_namespaces]]
binding = "SESSIONS"
id = "e8fdfb35962542efa34795d6371be808"
preview_id = "75c11e239fb746dda5a988d1a36d73f9"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "articles-logger-db"
database_id = "186dc78a-ddd7-464a-a32d-305bd625fa1d"
